### ISSUE TITLE
Trim down the frontend

### ISSUE THREAD

**Issue by ehharvey** [CSCN73030-projectv-group9/Attendance#112]
Our frontend has a few extra buttons, etc. that aren't part of our requirements.

Let's trim it down before proceeding further:
![image](https://user-images.githubusercontent.com/36806437/204294122-46bf9a3b-7b8c-4056-b3c3-6fc84db816ca.png)

**Comment by colefoster** [comment]
![image](https://user-images.githubusercontent.com/71045117/204654042-35839611-d18c-4e6b-ba4d-0e3c71376136.png)
