### ISSUE TITLE
Frontend Redesign

### ISSUE THREAD

**Issue by colefoster** [CSCN73030-projectv-group9/Attendance#119]
![20221129_190753](https://user-images.githubusercontent.com/71045117/204904774-479f7fd0-3e5e-48e1-ac08-4f38c286d39c.jpg)

We want to redesign the frontend to use a single page.
- [ ] 1 drop down where the user can select a completed or new attendance
- [ ] When the user selects any attendance, they can view, edit, or create the record from the same page

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/204924057-7fe68435-345d-495e-8a3f-72a131541858.png)
