### ISSUE TITLE
The Backend shall incorporate dependency injection

### ISSUE THREAD

**Issue by Amanuel-Negussie** [CSCN73030-projectv-group9/Attendance#21]
We want to be able to test our backend completely. To allow for this, we need dependency injection 😛 

This follows the same approach as the 'auteline' app for Software Quality III. In short, we want our class constructors to be able to receive any needed dependencies. We want to wrap any needed functionality in classes ideally.

In the Database, we need to be able to create and read files. This is something suitable for injection. Maybe we can wrap the creating and reading files in a separate class.

**Comment by ehharvey** [comment]
As discussed, we only need to supply a `Path` object (no need for `open`, `mkdir`, etc. mocks). Python `Path` objects have those functions builtin

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/200928457-d045ef1e-b97f-41e2-9ba8-148a4d8e2967.png)

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/200928684-e3853900-2ad6-45ef-ad7d-8688ac913e5a.png)

**Comment by ehharvey** [comment]
I got the code working but the assert part of the test is failing
![image](https://user-images.githubusercontent.com/36806437/200929570-ab7c6bfc-2bfa-41b0-91cd-913183fca8d6.png)

**Comment by ehharvey** [comment]
Whew got it working! Check out 11ac8c30329c5d85a08ebfd7e56f6c0c94463a82

Basically, we need to use patching to "patch" the functions. I'm not too sure how it works, but it's readable. See the commit link for my comments on this approach :fireworks:
