### ISSUE TITLE
Implement unit testing for Javascript

### ISSUE THREAD

**Issue by colefoster** [CSCN73030-projectv-group9/Attendance#28]
Decided on Jest as a testing framework. Successfully implemented a placeholder test, now working on testing for console output from functions.

**Comment by ehharvey** [comment]
Links from chat:
https://stackoverflow.com/questions/44302573/module-exports-multiple-functions-in-jest-testing
https://www.sitepoint.com/understanding-module-exports-exports-node-js/

**Comment by colefoster** [comment]
Decided on returning a value from the functions instead of checking for console logs
