### ISSUE TITLE
The Backend shall serve either the Professor or Student View based on the current setting in Admin Activities

### ISSUE THREAD

**Issue by ehharvey** [CSCN73030-projectv-group9/Attendance#89]
`GET /modeofoperation` (to Admin Activities) returns `True` in Professor view and `False` for Student View. Currently, our Backend always serves the professor view.

For this task, we want to selectively return the right view based on the return for Admin Activities.

When a web browser connects, the **backend should**:
1. Issue a request to admin activities
2. Use the response to ^^ to determine which page to send
3. Send the appropriate page.

Affected modules:
* REST API (app.py)
* ExternalConnector

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/203879607-d2ef080e-ac4a-4666-9dc5-079f1a764bb7.png)

**Comment by Amanuel-Negussie** [comment]
![image](https://user-images.githubusercontent.com/74369791/204019643-7cde7a02-5596-4ffe-ae99-d8ab3010c438.png)
For Get /modeofoperation the response json will be 
{
    "modeofoperation": true
}

for prof/teacher view 

and 
{
"modeofoperation":false
}

**Comment by ehharvey** [comment]
![image](https://user-images.githubusercontent.com/36806437/204020691-6635fc73-4b89-453c-863f-813a66834386.png)
